// src/app/categories/page.tsx
import { Metadata } from 'next';
import CategoriesPageClient from './categories-page-client';
import { theoryService, type CategoryStat } from '@/lib/theoryService';

export const metadata: Metadata = {
  title: 'Theory Categories - Ridiculous Rumors',
  description: 'Browse all conspiracy theory categories including Absurd Science, Historical Lies, Celebrity Secrets, and more. All content is fictional and for entertainment only.',
  keywords: [
    'conspiracy theory categories',
    'fictional theories',
    'comedy',
    'satire',
    'entertainment',
    'AI generated content'
  ],
  
  openGraph: {
    type: 'website',
    title: 'Theory Categories - Ridiculous Rumors',
    description: 'Explore all categories of hilarious fictional conspiracy theories generated by AI.',
    url: '/categories',
  },

  twitter: {
    card: 'summary_large_image',
    title: 'Theory Categories - Ridiculous Rumors',
    description: 'Browse fictional conspiracy theory categories for entertainment.',
  },

  alternates: {
    canonical: '/categories',
  },
};

export default async function CategoriesPage() {
  // Get category statistics with proper typing
  let categoryStats: CategoryStat[] = [];
  try {
    categoryStats = await theoryService.getCategoryStats();
  } catch (error) {
    console.error('Error fetching category stats:', error);
    // categoryStats remains as empty array with proper typing
  }

  return <CategoriesPageClient initialStats={categoryStats} />;
}