import type { Metadata } from "next";
import { JetBrains_Mono, Orbitron } from 'next/font/google';
import "./globals.css";

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains",
  subsets: ['latin'] 
})
const orbitron = Orbitron({ 
  variable: "--font-orbitron",
  subsets: ['latin'] 
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jetbrainsMono.variable} ${orbitron.variable}`}>
        {children}
      </body>
    </html>
  );
}
